name: LettersToCascadia
favicon: null
layout_spectrum: 1
typography_spectrum: 0
title: Letters to Cascadia
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#360468'
    - '#a0a5a9'
    - '#0791f5'
    - '#0738fe'
    - '#e3e3e3'
  brandStrength: 0.9685702251736075
  lightness: 0.28480472206138074
  saturation: 0.030870032496750355
  rhythmicContrast: 0.6379566960968077
purpose: []
